name: Publish WebComponents package to GitHub Packages
on:
  push:
    branches: ["main"]
    paths:
      - 'packages/web-components/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@northprim'
      - run: npm ci -w @northprim/web-components
      - run: npm publish -w @northprim/web-components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
